import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import useStore from '../store/useStore';
import { decksApi, notesApi, aiApi } from '../services/api';
import { handleImagePaste, compressImageFromPaste } from '../utils/imageUtils';
import { lookupDefinition, lookupImage } from '../utils/definitionService';
import ImageSearchModal from '../components/ImageSearchModal';
import { Button } from '../components/ui/button';
import { Badge } from '../components/ui/badge';
import { Card, CardContent } from '../components/ui/card';
import { Input } from '../components/ui/input';

const NOTE_TYPES = [
  { id: 'basic', name: 'Básica', description: 'Frente y dorso simple', fields: ['front', 'back'], cardsGenerated: 1 },
  { id: 'reverse', name: 'Básica + Reversa', description: 'Genera 2 tarjetas', fields: ['front', 'back'], cardsGenerated: 2 },
];

const formatMovedText = (html) => {
  const text = (html || '').replace(/<[^>]*>/g, '').trim();
  if (!text) return '';
  const titleCased = text.split(/\s+/).map(w => w.charAt(0).toUpperCase() + w.toLowerCase().slice(1)).join(' ');
  return `<div style="font-size: 1.25em; text-align: center;" data-auto="true"><strong>${titleCased}</strong></div>`;
};

const isAutoGenerated = (html) => {
  if (typeof html !== 'string') return false;
  return html.includes('data-auto="true"');
};

function AddCard() {
  const { deckId: paramDeckId } = useParams();
  const navigate = useNavigate();
  const { addToast } = useStore();
  
  const [decks, setDecks] = useState([]);
  const [selectedDeckId, setSelectedDeckId] = useState(paramDeckId || '');
  const [selectedType, setSelectedType] = useState('basic');
  const [addMode, setAddMode] = useState('single');
  const [fields, setFields] = useState({ front: '', back: '' });
  const [tags, setTags] = useState([]);
  const [tagInput, setTagInput] = useState('');
  const [massInput, setMassInput] = useState('');
  const [saving, setSaving] = useState(false);
  const [massGenerating, setMassGenerating] = useState(false);
  
  const [lookingUpDef, setLookingUpDef] = useState(false);
  const [lookingUpImage, setLookingUpImage] = useState(false);

  const [imageSearchModalInfo, setImageSearchModalInfo] = useState(null);
  
  const frontFileRef = useRef(null);
  const backFileRef = useRef(null);
  const tagInputRef = useRef(null);
  const frontContentRef = useRef(null);
  const backContentRef = useRef(null);

  useEffect(() => {
    decksApi.getAll().then(data => {
      setDecks(data);
      if (!selectedDeckId && data.length > 0) setSelectedDeckId(data[0].id);
    });
  }, []);

  const clearEditor = () => {
    setFields({ front: '', back: '' });
    if (frontContentRef.current) frontContentRef.current.innerHTML = '';
    if (backContentRef.current) backContentRef.current.innerHTML = '';
  };

  const insertHtmlAtCursor = (html, contentRef) => {
    contentRef.current.focus();
    let selection = window.getSelection();
    let range = selection.getRangeAt(0);
    
    const isWithinRef = contentRef.current.contains(range.commonAncestorContainer);
    if (!isWithinRef) {
      range = document.createRange();
      range.selectNodeContents(contentRef.current);
      range.collapse(false);
      selection.removeAllRanges();
      selection.addRange(range);
    }
    
    range.deleteContents();
    const el = document.createElement("div");
    el.innerHTML = html;
    const frag = document.createDocumentFragment();
    let node, lastNode;
    while ((node = el.firstChild)) {
      lastNode = frag.appendChild(node);
    }
    range.insertNode(frag);
    if (lastNode) {
      range = range.cloneRange();
      range.setStartAfter(lastNode);
      range.collapse(true);
      selection.removeAllRanges();
      selection.addRange(range);
    }
  };

  const handleFieldChange = (field) => (e) => {
    let content = e.target.innerHTML;
    if (content === '<br>') content = '';
    
    if (field === 'back' && isAutoGenerated(fields.front) && !content) {
      const movedHtml = formatMovedText(fields.front);
      setFields(prev => ({ ...prev, front: '', back: movedHtml }));
      if (frontContentRef.current) frontContentRef.current.innerHTML = '';
      if (backContentRef.current) backContentRef.current.innerHTML = movedHtml;
      setTimeout(() => {
        const sel = window.getSelection();
        const range = document.createRange();
        range.selectNodeContents(backContentRef.current);
        range.collapse(false);
        sel.removeAllRanges();
        sel.addRange(range);
      }, 0);
      return;
    }
    
    setFields(prev => ({ ...prev, [field]: content }));
  };

  const handlePaste = (field) => async (e) => {
    handleImagePaste(e, async (base64) => {
      const imgHtml = `<img src="${base64}" />`;
      if (field === 'front') insertHtmlAtCursor(imgHtml, frontContentRef);
      else insertHtmlAtCursor(imgHtml, backContentRef);
      setFields(prev => ({ ...prev, [field]: field === 'front' ? frontContentRef.current.innerHTML : backContentRef.current.innerHTML }));
    });
  };

  const handleFileSelected = (field, e) => {
    const file = e.target.files[0];
    if (!file) return;
    compressImageFromPaste(file, (base64) => {
      const imgHtml = `<img src="${base64}" />`;
      if (field === 'front') insertHtmlAtCursor(imgHtml, frontContentRef);
      else insertHtmlAtCursor(imgHtml, backContentRef);
      setFields(prev => ({ ...prev, [field]: field === 'front' ? frontContentRef.current.innerHTML : backContentRef.current.innerHTML }));
      e.target.value = null;
    });
  };

  const handleGalleryPick = (field) => {
    if (field === 'front') frontFileRef.current?.click();
    else backFileRef.current?.click();
  };

  const handleOpenImageSearch = (field) => {
    const query = (fields[field] || '').replace(/<[^>]*>/g, '').trim() || (field === 'back' ? (fields.front || '').replace(/<[^>]*>/g, '').trim() : '');
    setImageSearchModalInfo({ field, query });
  };

  const handleImageSearchSelect = (base64, field) => {
    const imgHtml = `<img src="${base64}" />`;
    if (field === 'front') insertHtmlAtCursor(imgHtml, frontContentRef);
    else insertHtmlAtCursor(imgHtml, backContentRef);
    setFields(prev => ({ ...prev, [field]: field === 'front' ? frontContentRef.current.innerHTML : backContentRef.current.innerHTML }));
  };

  const handleDefinition = async () => {
    let term = (fields.front || '').replace(/<[^>]*>/g, '').trim();
    if (!term) return addToast('Escribe un término en el frente primero', 'error');
    setLookingUpDef(true);
    try {
      const def = await lookupDefinition(term);
      if (backContentRef.current) backContentRef.current.innerHTML = def;
      setFields(prev => ({ ...prev, back: def }));
    } catch (e) {
      addToast(e.message, 'error');
    } finally {
      setLookingUpDef(false);
    }
  };

  const handleAutoImage = async () => {
    let term = (fields.front || '').replace(/<[^>]*>/g, '').trim();
    if (!term) return addToast('Escribe un término en el frente primero', 'error');
    setLookingUpImage(true);
    try {
      const base64 = await lookupImage(term);
      if (base64) {
        handleImageSearchSelect(base64, 'front');
      } else {
        addToast('No se encontró imagen', 'error');
      }
    } catch (e) {
      addToast(e.message, 'error');
    } finally {
      setLookingUpImage(false);
    }
  };

  const handleAdd = async (closeAfter) => {
    if (!selectedDeckId) return addToast('Selecciona un mazo', 'error');
    if (!fields.front.trim() || !fields.back.trim()) return addToast('El frente y el dorso son obligatorios', 'error');
    
    setSaving(true);
    try {
      await notesApi.create({
        deckId: selectedDeckId,
        noteType: selectedType,
        fieldsJson: JSON.stringify({ front: fields.front, back: fields.back }),
        tags: tags.join(',')
      });
      addToast('Tarjeta añadida', 'success');
      clearEditor();
      if (closeAfter) navigate(-1);
    } catch (e) {
      addToast('Error al añadir', 'error');
    } finally {
      setSaving(false);
    }
  };

  const handleMassAdd = async () => {
    if (!selectedDeckId) return addToast('Selecciona un mazo', 'error');
    if (!massInput.trim()) return addToast('Escribe al menos un concepto', 'error');
    
    setMassGenerating(true);
    try {
      const concepts = massInput.split(/[\n,]+/).map(s => s.trim()).filter(s => s.length > 0);
      if (concepts.length === 0) throw new Error("No hay conceptos válidos");
      if (concepts.length > 30) throw new Error("Máximo 30 conceptos por lote");
      
      const response = await aiApi.generateMassCards(concepts);
      
      let count = 0;
      for (const card of response.cards) {
        await notesApi.create({
          deckId: selectedDeckId,
          noteType: 'basic',
          fieldsJson: JSON.stringify({ front: card.front, back: card.back }),
          tags: tags.join(',')
        });
        count++;
      }
      
      addToast(`¡Generadas ${count} tarjetas!`, 'success');
      setMassInput('');
    } catch (e) {
      addToast('Error al generar masa: ' + e.message, 'error');
    } finally {
      setMassGenerating(false);
    }
  };

  const handleTagKeyDown = (e) => {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault();
      const tag = tagInput.trim().toLowerCase().replace(/[^a-z0-9-]/g, '');
      if (tag && !tags.includes(tag)) setTags([...tags, tag]);
      setTagInput('');
    } else if (e.key === 'Backspace' && tagInput === '' && tags.length > 0) {
      setTags(tags.slice(0, -1));
    }
  };
  const removeTag = (t) => setTags(tags.filter(x => x !== t));

  useEffect(() => {
    const handler = (e) => {
      if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) { 
        e.preventDefault(); 
        if (addMode === 'single') handleAdd(false); 
        else handleMassAdd();
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [fields, selectedDeckId, selectedType, tags, massInput]);

  return (
    <div className="animate-in fade-in pb-20">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold tracking-tight">Añadir Tarjetas</h1>
        <div className="flex bg-secondary p-1 rounded-xl">
          <Button 
            variant={addMode === 'single' ? 'default' : 'ghost'}
            size="sm"
            className="rounded-lg h-8"
            onClick={() => setAddMode('single')}
          >
            Una a Una
          </Button>
          <Button 
            variant={addMode === 'mass' ? 'default' : 'ghost'}
            size="sm"
            className="rounded-lg h-8"
            onClick={() => setAddMode('mass')}
          >
            ✨ En Masa (IA)
          </Button>
        </div>
      </div>

      <input ref={frontFileRef} type="file" accept="image/*" className="hidden" onChange={(e) => handleFileSelected('front', e)} />
      <input ref={backFileRef} type="file" accept="image/*" className="hidden" onChange={(e) => handleFileSelected('back', e)} />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-semibold">Mazo</label>
          <select 
            className="flex h-11 w-full rounded-md border border-input bg-secondary px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
            value={selectedDeckId} 
            onChange={e => setSelectedDeckId(e.target.value)}
          >
            <option value="">Seleccionar mazo...</option>
            {decks.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}
          </select>
        </div>
        {addMode === 'single' && (
          <div className="flex flex-col gap-1.5">
            <label className="text-sm font-semibold">Tipo de nota</label>
            <select 
              className="flex h-11 w-full rounded-md border border-input bg-secondary px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
              value={selectedType} 
              onChange={e => { setSelectedType(e.target.value); clearEditor(); }}
            >
              {NOTE_TYPES.map(t => <option key={t.id} value={t.id}>{t.name} — {t.description}</option>)}
            </select>
          </div>
        )}
      </div>

      {addMode === 'mass' ? (
        <Card className="bg-card">
          <CardContent className="p-6">
            <div className="bg-blue-500/10 border border-blue-500/20 rounded-xl p-4 mb-6">
              <h3 className="font-semibold text-blue-400 mb-1">✨ Generación Mágica con Inteligencia Artificial</h3>
              <p className="text-sm text-blue-200/70">
                Escribe o pega una lista de conceptos, palabras clave o frases (separados por comas o saltos de línea). La IA se encargará de buscar una definición súper breve para cada uno y creará todas las tarjetas de golpe.
              </p>
            </div>
            
            <div className="flex flex-col gap-2 mb-6">
              <label className="text-sm font-semibold">Lista de Conceptos</label>
              <textarea
                className="flex min-h-[200px] w-full rounded-md border border-input bg-secondary px-3 py-2 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                value={massInput}
                onChange={e => setMassInput(e.target.value)}
                placeholder="Ejemplo:&#10;Polimorfismo&#10;Herencia&#10;Encapsulación&#10;Abstracción"
              />
            </div>
            
            <Button 
              size="lg" 
              className="w-full h-12" 
              onClick={handleMassAdd}
              disabled={massGenerating}
            >
              {massGenerating ? 'Generando...' : '✨ Generar y Añadir Tarjetas (Ctrl+Enter)'}
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="flex flex-col gap-6">
            <div className="flex flex-col gap-2">
              <div className="flex justify-between items-center mb-1 flex-wrap gap-2">
                <label className="text-sm font-semibold">Frente (Pregunta)</label>
                <div className="flex gap-1">
                  <Button variant="secondary" size="sm" className="h-7 text-xs px-2" onClick={handleDefinition}>
                    {lookingUpDef ? '...' : '✨ Def. IA'}
                  </Button>
                  <Button variant="secondary" size="sm" className="h-7 text-xs px-2" onClick={handleAutoImage}>
                    {lookingUpImage ? '...' : '✨ Foto Auto'}
                  </Button>
                  <Button variant="secondary" size="sm" className="h-7 text-xs px-2" onClick={() => handleGalleryPick('front')} title="Galería">🖼️</Button>
                  <Button variant="secondary" size="sm" className="h-7 text-xs px-2" onClick={() => handleOpenImageSearch('front')} title="Wikipedia">🔍 Buscar</Button>
                </div>
              </div>
              <div 
                className="min-h-[120px] rounded-xl border border-input bg-secondary p-3 text-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring prose prose-invert max-w-none" 
                contentEditable 
                ref={frontContentRef}
                onInput={handleFieldChange('front')} 
                onPaste={handlePaste('front')}
              />
            </div>

            <div className="flex flex-col gap-2">
              <div className="flex justify-between items-center mb-1 flex-wrap gap-2">
                <label className="text-sm font-semibold">Dorso (Respuesta)</label>
                <div className="flex gap-1">
                  <Button variant="secondary" size="sm" className="h-7 text-xs px-2" onClick={() => handleGalleryPick('back')} title="Galería">🖼️</Button>
                  <Button variant="secondary" size="sm" className="h-7 text-xs px-2" onClick={() => handleOpenImageSearch('back')} title="Wikipedia">🔍 Buscar</Button>
                </div>
              </div>
              <div 
                className="min-h-[120px] rounded-xl border border-input bg-secondary p-3 text-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring prose prose-invert max-w-none" 
                contentEditable 
                ref={backContentRef}
                onInput={handleFieldChange('back')} 
                onPaste={handlePaste('back')}
              />
            </div>

            <div className="flex flex-col gap-2">
              <label className="text-sm font-semibold">Etiquetas</label>
              <div className="flex flex-wrap items-center gap-2 p-2 rounded-xl border border-input bg-secondary min-h-[44px]" onClick={() => tagInputRef.current?.focus()}>
                {tags.map(tag => (
                  <Badge key={tag} variant="default" className="flex items-center gap-1">
                    {tag}
                    <span className="cursor-pointer opacity-70 hover:opacity-100" onClick={(e) => { e.stopPropagation(); removeTag(tag); }}>×</span>
                  </Badge>
                ))}
                <input
                  ref={tagInputRef}
                  className="flex-1 min-w-[120px] bg-transparent border-none outline-none text-sm placeholder:text-muted-foreground"
                  placeholder={tags.length === 0 ? 'Añadir etiquetas...' : ''}
                  value={tagInput}
                  onChange={e => setTagInput(e.target.value)}
                  onKeyDown={handleTagKeyDown}
                />
              </div>
            </div>

            <div className="flex gap-3 mt-2">
              <Button size="lg" className="flex-1" onClick={() => handleAdd(false)} disabled={saving}>
                {saving ? 'Guardando...' : 'Añadir'}
                <span className="opacity-50 text-xs ml-2 hidden sm:inline">Ctrl+Enter</span>
              </Button>
              <Button size="lg" variant="secondary" onClick={() => handleAdd(true)} disabled={saving}>
                Añadir y Cerrar
              </Button>
            </div>
          </div>

          <div className="hidden lg:flex flex-col">
            <div className="text-xs font-bold text-muted-foreground uppercase tracking-widest mb-3">Vista Previa</div>
            <Card className="bg-card flex-1 min-h-[400px]">
              <CardContent className="p-6 h-full flex flex-col">
                <div className="prose prose-invert max-w-none text-center" dangerouslySetInnerHTML={{ __html: fields.front || '<span class="text-muted-foreground">Pregunta...</span>' }} />
                <div className="h-px w-2/3 bg-border mx-auto my-6" />
                <div className="prose prose-invert max-w-none text-center flex-1" dangerouslySetInnerHTML={{ __html: fields.back || '<span class="text-muted-foreground">Respuesta...</span>' }} />
                {tags.length > 0 && (
                  <div className="flex flex-wrap gap-1 justify-center mt-6 pt-4 border-t border-border/50">
                    {tags.map(tag => <Badge key={tag} variant="outline" className="text-[10px]">{tag}</Badge>)}
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      )}

      {imageSearchModalInfo && (
        <ImageSearchModal
          query={imageSearchModalInfo.query}
          onSelect={(base64) => handleImageSearchSelect(base64, imageSearchModalInfo.field)}
          onClose={() => setImageSearchModalInfo(null)}
        />
      )}
    </div>
  );
}

export default AddCard;
