import { useState, useEffect, useRef, KeyboardEvent } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import useStore from '../store/useStore';
import { decksApi, notesApi, aiApi } from '../services/api';
import { handleImagePaste, compressImageFromPaste } from '../utils/imageUtils';
import { lookupDefinition, lookupImage } from '../utils/definitionService';
import ImageSearchModal from '../components/ImageSearchModal';
import { Deck } from '../types';

const NOTE_TYPES = [
  { id: 'basic', name: 'Básica', description: 'Frente y dorso simple' },
  { id: 'reverse', name: 'Básica + Reversa', description: 'Genera 2 tarjetas' },
];

const formatMovedText = (html: string) => {
  const text = (html || '').replace(/<[^>]*>/g, '').trim();
  if (!text) return '';
  const titleCased = text.split(/\s+/).map(w => w.charAt(0).toUpperCase() + w.toLowerCase().slice(1)).join(' ');
  return `<div style="font-size: 1.25em; text-align: center;" data-auto="true"><strong>${titleCased}</strong></div>`;
};

const isAutoGenerated = (html: string) => {
  if (typeof html !== 'string') return false;
  return html.includes('data-auto="true"');
};

export default function AddCard() {
  const { deckId: paramDeckId } = useParams<{ deckId: string }>();
  const navigate = useNavigate();
  const { addToast } = useStore();
  
  const [decks, setDecks] = useState<Deck[]>([]);
  const [selectedDeckId, setSelectedDeckId] = useState<string>(paramDeckId || '');
  const [selectedType, setSelectedType] = useState<string>('basic');
  const [addMode, setAddMode] = useState<'single' | 'mass'>('single');
  const [fields, setFields] = useState({ front: '', back: '' });
  const [tags, setTags] = useState<string[]>([]);
  const [tagInput, setTagInput] = useState<string>('');
  const [massInput, setMassInput] = useState<string>('');
  const [saving, setSaving] = useState<boolean>(false);
  const [massGenerating, setMassGenerating] = useState<boolean>(false);
  
  const [lookingUpDef, setLookingUpDef] = useState<boolean>(false);
  const [lookingUpImage, setLookingUpImage] = useState<boolean>(false);

  const [imageSearchModalInfo, setImageSearchModalInfo] = useState<{ field: 'front' | 'back', query: string } | null>(null);
  
  const frontFileRef = useRef<HTMLInputElement>(null);
  const backFileRef = useRef<HTMLInputElement>(null);
  const tagInputRef = useRef<HTMLInputElement>(null);
  const frontContentRef = useRef<HTMLDivElement>(null);
  const backContentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    decksApi.getAll().then(data => {
      setDecks(data);
      if (!selectedDeckId && data.length > 0) setSelectedDeckId(data[0].id);
    });
  }, [selectedDeckId]);

  const clearEditor = () => {
    setFields({ front: '', back: '' });
    if (frontContentRef.current) frontContentRef.current.innerHTML = '';
    if (backContentRef.current) backContentRef.current.innerHTML = '';
  };

  const insertHtmlAtCursor = (html: string, contentRef: React.RefObject<HTMLDivElement | null>) => {
    if (!contentRef.current) return;
    contentRef.current.focus();
    let selection = window.getSelection();
    if (!selection || selection.rangeCount === 0) return;
    let range = selection.getRangeAt(0);
    
    const isWithinRef = contentRef.current.contains(range.commonAncestorContainer);
    if (!isWithinRef) {
      range = document.createRange();
      range.selectNodeContents(contentRef.current);
      range.collapse(false);
      selection.removeAllRanges();
      selection.addRange(range);
    }
    
    range.deleteContents();
    const el = document.createElement("div");
    el.innerHTML = html;
    const frag = document.createDocumentFragment();
    let node, lastNode;
    while ((node = el.firstChild)) {
      lastNode = frag.appendChild(node);
    }
    range.insertNode(frag);
    if (lastNode) {
      range = range.cloneRange();
      range.setStartAfter(lastNode);
      range.collapse(true);
      selection.removeAllRanges();
      selection.addRange(range);
    }
  };

  const handleFieldChange = (field: 'front' | 'back') => (e: React.FormEvent<HTMLDivElement>) => {
    let content = e.currentTarget.innerHTML;
    if (content === '<br>') content = '';
    
    if (field === 'back' && isAutoGenerated(fields.front) && !content) {
      const movedHtml = formatMovedText(fields.front);
      setFields(prev => ({ ...prev, front: '', back: movedHtml }));
      if (frontContentRef.current) frontContentRef.current.innerHTML = '';
      if (backContentRef.current) backContentRef.current.innerHTML = movedHtml;
      setTimeout(() => {
        const sel = window.getSelection();
        if (!sel || !backContentRef.current) return;
        const range = document.createRange();
        range.selectNodeContents(backContentRef.current);
        range.collapse(false);
        sel.removeAllRanges();
        sel.addRange(range);
      }, 0);
      return;
    }
    
    setFields(prev => ({ ...prev, [field]: content }));
  };

  const handlePaste = (field: 'front' | 'back') => async (e: React.ClipboardEvent<HTMLDivElement>) => {
    handleImagePaste(e, () => {
      setFields(prev => ({ ...prev, [field]: field === 'front' && frontContentRef.current ? frontContentRef.current.innerHTML : backContentRef.current ? backContentRef.current.innerHTML : '' }));
    });
  };

  const handleFileSelected = (field: 'front' | 'back', e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    compressImageFromPaste(file).then((base64: string) => {
      const imgHtml = `<img src="${base64}" />`;
      if (field === 'front') insertHtmlAtCursor(imgHtml, frontContentRef);
      else insertHtmlAtCursor(imgHtml, backContentRef);
      setFields(prev => ({ ...prev, [field]: field === 'front' && frontContentRef.current ? frontContentRef.current.innerHTML : backContentRef.current ? backContentRef.current.innerHTML : '' }));
      e.target.value = '';
    });
  };

  const handleGalleryPick = (field: 'front' | 'back') => {
    if (field === 'front') frontFileRef.current?.click();
    else backFileRef.current?.click();
  };

  const handleOpenImageSearch = (field: 'front' | 'back') => {
    const query = (fields[field] || '').replace(/<[^>]*>/g, '').trim() || (field === 'back' ? (fields.front || '').replace(/<[^>]*>/g, '').trim() : '');
    setImageSearchModalInfo({ field, query });
  };

  const handleImageSearchSelect = (base64: string, field: 'front' | 'back') => {
    const imgHtml = `<img src="${base64}" />`;
    if (field === 'front') insertHtmlAtCursor(imgHtml, frontContentRef);
    else insertHtmlAtCursor(imgHtml, backContentRef);
    setFields(prev => ({ ...prev, [field]: field === 'front' && frontContentRef.current ? frontContentRef.current.innerHTML : backContentRef.current ? backContentRef.current.innerHTML : '' }));
  };

  const handleDefinition = async () => {
    const term = (fields.front || '').replace(/<[^>]*>/g, '').trim();
    if (!term) return addToast('Escribe un término en el frente primero', 'error');
    setLookingUpDef(true);
    try {
      const def = await lookupDefinition(term);
      if (def?.definition) {
        if (backContentRef.current) backContentRef.current.innerHTML = def.definition;
        setFields(prev => ({ ...prev, back: def.definition }));
      }
    } catch (e: unknown) {
      addToast(e instanceof Error ? e.message : 'Error buscando definicion', 'error');
    } finally {
      setLookingUpDef(false);
    }
  };

  const handleAutoImage = async () => {
    const term = (fields.front || '').replace(/<[^>]*>/g, '').trim();
    if (!term) return addToast('Escribe un término en el frente primero', 'error');
    setLookingUpImage(true);
    try {
      const url = await lookupImage(term);
      if (url) {
        handleImageSearchSelect(url, 'front');
      } else {
        addToast('No se encontró imagen', 'error');
      }
    } catch (e: unknown) {
      addToast(e instanceof Error ? e.message : 'Error buscando imagen', 'error');
    } finally {
      setLookingUpImage(false);
    }
  };

  const handleAdd = async (closeAfter: boolean) => {
    if (!selectedDeckId) return addToast('Selecciona un mazo', 'error');
    if (!fields.front.trim() || !fields.back.trim()) return addToast('El frente y el dorso son obligatorios', 'error');
    
    setSaving(true);
    try {
      const fieldsJson = JSON.stringify({ front: fields.front, back: fields.back });
      await notesApi.create({
        deckId: selectedDeckId,
        noteType: selectedType,
        fieldsJson,
        tags: tags.join(',')
      });
      addToast('Tarjeta añadida', 'success');
      clearEditor();
      if (closeAfter) navigate('/');
    } catch (e: unknown) {
      addToast(e instanceof Error ? e.message : 'Error al guardar', 'error');
    } finally {
      setSaving(false);
    }
  };

  const handleMassAdd = async () => {
    if (!massInput.trim() || !selectedDeckId) return;
    setMassGenerating(true);
    try {
      const lines = massInput.split(/[\n,]+/).map(s => s.trim()).filter(Boolean);
      if (lines.length === 0) return;
      
      const res = await aiApi.massDefine(lines.join('\n')) as unknown as { front: string; back: string; }[];
      if (!res || !Array.isArray(res) || res.length === 0) {
        throw new Error('No se generaron tarjetas');
      }
      
      let count = 0;
      for (const card of res) {
        await notesApi.create({
          deckId: selectedDeckId,
          noteType: 'basic',
          fieldsJson: JSON.stringify({ front: card.front, back: card.back }),
          tags: tags.join(',')
        });
        count++;
      }
      
      addToast(`¡Generadas ${count} tarjetas!`, 'success');
      setMassInput('');
    } catch (e: unknown) {
      addToast(e instanceof Error ? e.message : 'Error al generar masa', 'error');
    } finally {
      setMassGenerating(false);
    }
  };

  const handleTagKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault();
      const tag = tagInput.trim().toLowerCase().replace(/[^a-z0-9-]/g, '');
      if (tag && !tags.includes(tag)) setTags([...tags, tag]);
      setTagInput('');
    } else if (e.key === 'Backspace' && tagInput === '' && tags.length > 0) {
      setTags(tags.slice(0, -1));
    }
  };
  const removeTag = (t: string) => setTags(tags.filter(x => x !== t));

  useEffect(() => {
    const handler = (e: globalThis.KeyboardEvent) => {
      if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) { 
        e.preventDefault(); 
        if (addMode === 'single') handleAdd(false); 
        else handleMassAdd();
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [fields, selectedDeckId, selectedType, tags, massInput, addMode]);

  return (
    <div className="fade-in pb-10">
      <div className="sticky top-0 z-10 bg-background/80 backdrop-blur-xl pt-2 pb-4 mb-6 -mx-2 px-2 sm:mx-0 sm:px-0">
          <div className="bg-card border border-white/10 p-1.5 rounded-full flex items-center w-full max-w-md mx-auto shadow-lg">
            <button 
              className={`flex-1 rounded-full py-3 px-4 text-[0.95rem] font-bold transition-all ${addMode === 'single' ? 'bg-white/10 text-white shadow-sm border border-white/10' : 'text-muted-foreground hover:text-foreground hover:bg-white/5'}`}
              onClick={() => setAddMode('single')}
            >
              Una a Una
            </button>
            <button 
              className={`flex-1 rounded-full py-3 px-4 text-[0.95rem] font-bold transition-all ${addMode === 'mass' ? 'bg-white/10 text-white shadow-sm border border-white/10' : 'text-muted-foreground hover:text-foreground hover:bg-white/5'}`}
              onClick={() => setAddMode('mass')}
            >
              ? En Masa
            </button>
          </div>
        </div>
        <div className="card" style={{ padding: '1.5rem', marginBottom: '1.5rem' }}>

        <input ref={frontFileRef} type="file" accept="image/*" style={{ display: 'none' }} onChange={(e) => handleFileSelected('front', e)} />
        <input ref={backFileRef} type="file" accept="image/*" style={{ display: 'none' }} onChange={(e) => handleFileSelected('back', e)} />

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1rem', marginBottom: '1rem' }}>
          <div>
            <label style={{ display: 'block', fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: 6, fontWeight: 600 }}>MAZO</label>
            <select 
              className="form-input" 
              value={selectedDeckId} 
              onChange={e => setSelectedDeckId(e.target.value)}
              style={{ width: '100%', height: '42px' }}
            >
              <option value="">Seleccionar mazo...</option>
              {decks.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}
            </select>
          </div>
          
          {addMode === 'single' && (
            <div>
              <label style={{ display: 'block', fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: 6, fontWeight: 600 }}>TIPO DE NOTA</label>
              <select 
                className="form-input" 
                value={selectedType} 
                onChange={e => { setSelectedType(e.target.value); clearEditor(); }}
                style={{ width: '100%', height: '42px' }}
              >
                {NOTE_TYPES.map(t => <option key={t.id} value={t.id}>{t.name} — {t.description}</option>)}
              </select>
            </div>
          )}
        </div>
      </div>

      {addMode === 'mass' ? (
        <div className="card" style={{ padding: '1.5rem', marginBottom: '1.5rem' }}>
          <div style={{ background: 'rgba(59, 130, 246, 0.1)', border: '1px solid rgba(59, 130, 246, 0.2)', borderRadius: '12px', padding: '16px', marginBottom: '24px' }}>
            <h3 style={{ margin: '0 0 8px 0', color: '#60a5fa' }}>✨ Generación Mágica con Inteligencia Artificial</h3>
            <p style={{ margin: 0, fontSize: '0.9rem', color: 'var(--text-dim)' }}>
              Escribe o pega una lista de conceptos, palabras clave o frases (separados por comas o saltos de línea). La IA se encargará de buscar una definición súper breve para cada uno y creará todas las tarjetas de golpe.
            </p>
          </div>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', marginBottom: '24px' }}>
            <label style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-muted)' }}>Lista de Conceptos</label>
            <textarea
              className="form-input"
              style={{ minHeight: '200px', padding: '12px', resize: 'vertical' }}
              value={massInput}
              onChange={e => setMassInput(e.target.value)}
              placeholder="Ejemplo:&#10;Polimorfismo&#10;Herencia&#10;Encapsulación&#10;Abstracción"
            />
          </div>
          
          <button 
            className="primary-btn" 
            style={{ width: '100%', padding: '16px', fontSize: '1.1rem' }} 
            onClick={handleMassAdd}
            disabled={massGenerating}
          >
            {massGenerating ? <span className="spinner-sm" /> : '✨ Generar y Añadir Tarjetas (Ctrl+Enter)'}
          </button>
        </div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', gap: '1.5rem' }}>
          
          <div className="card" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
            {/* Front */}
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8, flexWrap: 'wrap', gap: '8px' }}>
                <label style={{ margin: 0, fontSize: '0.85rem', color: 'var(--text-muted)', fontWeight: 600 }}>FRENTE (PREGUNTA)</label>
                  <div style={{ display: 'flex', gap: '8px' }}>
                    <button className="bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-md px-3 py-1.5 text-xs font-medium transition-colors flex items-center gap-1" onClick={handleDefinition} disabled={lookingUpDef}>
                      {lookingUpDef ? '...' : '✨ Def. IA'}
                    </button>
                    <button className="bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-md px-3 py-1.5 text-xs font-medium transition-colors flex items-center gap-1" onClick={handleAutoImage} disabled={lookingUpImage}>
                      {lookingUpImage ? '...' : '📸 Foto Auto'}
                    </button>
                    <button className="bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-md px-3 py-1.5 text-xs font-medium transition-colors flex items-center gap-1" onClick={() => handleGalleryPick('front')} title="Galería">🖼️</button>
                    <button className="bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-md px-3 py-1.5 text-xs font-medium transition-colors flex items-center gap-1" onClick={() => handleOpenImageSearch('front')} title="Wikipedia">🔍 Buscar</button>
                  </div>
              </div>
              <div 
                className="form-input" 
                style={{ minHeight: '120px', padding: '12px', fontSize: '1rem', lineHeight: 1.5, background: 'var(--bg-card)', borderRadius: '12px' }}
                contentEditable 
                ref={frontContentRef}
                onInput={handleFieldChange('front')} 
                onPaste={handlePaste('front')}
              />
            </div>

            {/* Back */}
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8, flexWrap: 'wrap', gap: '8px' }}>
                <label style={{ margin: 0, fontSize: '0.85rem', color: 'var(--text-muted)', fontWeight: 600 }}>DORSO (RESPUESTA)</label>
                  <div style={{ display: 'flex', gap: '8px' }}>
                    <button className="bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-md px-3 py-1.5 text-xs font-medium transition-colors flex items-center gap-1" onClick={() => handleGalleryPick('back')} title="Galería">🖼️</button>
                    <button className="bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-md px-3 py-1.5 text-xs font-medium transition-colors flex items-center gap-1" onClick={() => handleOpenImageSearch('back')} title="Wikipedia">🔍 Buscar</button>
                  </div>
              </div>
              <div 
                className="form-input" 
                style={{ minHeight: '120px', padding: '12px', fontSize: '1rem', lineHeight: 1.5, background: 'var(--bg-card)', borderRadius: '12px' }}
                contentEditable 
                ref={backContentRef}
                onInput={handleFieldChange('back')} 
                onPaste={handlePaste('back')}
              />
            </div>

            {/* Tags */}
            <div>
              <label style={{ display: 'block', fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: 8, fontWeight: 600 }}>ETIQUETAS</label>
              <div className="form-input" style={{ display: 'flex', flexWrap: 'wrap', gap: '8px', minHeight: '44px', padding: '8px 12px', alignItems: 'center' }} onClick={() => tagInputRef.current?.focus()}>
                {tags.map(tag => (
                  <span key={tag} style={{ background: 'var(--accent-color)', color: 'white', padding: '2px 8px', borderRadius: '12px', fontSize: '0.8rem', display: 'flex', alignItems: 'center', gap: '4px' }}>
                    {tag}
                    <span style={{ cursor: 'pointer', opacity: 0.7 }} onClick={(e) => { e.stopPropagation(); removeTag(tag); }}>×</span>
                  </span>
                ))}
                <input
                  ref={tagInputRef}
                  style={{ flex: 1, minWidth: '120px', background: 'transparent', border: 'none', outline: 'none', color: 'inherit' }}
                  placeholder={tags.length === 0 ? 'Añadir etiquetas...' : ''}
                  value={tagInput}
                  onChange={e => setTagInput(e.target.value)}
                  onKeyDown={handleTagKeyDown}
                />
              </div>
            </div>

            <div style={{ display: 'flex', gap: '12px', marginTop: '8px' }}>
              <button className="primary-btn" style={{ flex: 1 }} onClick={() => handleAdd(false)} disabled={saving}>
                {saving ? 'Guardando...' : 'Añadir (Ctrl+Enter)'}
              </button>
              <button className="btn btn-secondary" style={{ flex: 1 }} onClick={() => handleAdd(true)} disabled={saving}>
                Añadir y Cerrar
              </button>
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column' }}>
            <div style={{ fontSize: '0.75rem', fontWeight: 'bold', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '12px' }}>Vista Previa</div>
            <div className="card" style={{ flex: 1, padding: '1.5rem', display: 'flex', flexDirection: 'column', minHeight: '400px' }}>
              <div style={{ textAlign: 'center', fontSize: '1.1rem' }} dangerouslySetInnerHTML={{ __html: fields.front || '<span style="color:var(--text-dim)">Pregunta...</span>' }} />
              <div style={{ height: '1px', width: '66%', background: 'var(--border-color)', margin: '24px auto' }} />
              <div style={{ textAlign: 'center', fontSize: '1.1rem', flex: 1 }} dangerouslySetInnerHTML={{ __html: fields.back || '<span style="color:var(--text-dim)">Respuesta...</span>' }} />
              {tags.length > 0 && (
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px', justifyContent: 'center', marginTop: '24px', paddingTop: '16px', borderTop: '1px solid var(--border-color)' }}>
                  {tags.map(tag => <span key={tag} style={{ border: '1px solid var(--border-color)', padding: '2px 8px', borderRadius: '4px', fontSize: '0.7rem' }}>{tag}</span>)}
                </div>
              )}
            </div>
          </div>
          
        </div>
      )}

      {imageSearchModalInfo && (
        <ImageSearchModal
          isOpen={true}
          initialQuery={imageSearchModalInfo.query}
          onSelect={(base64: string) => handleImageSearchSelect(base64, imageSearchModalInfo.field)}
          onClose={() => setImageSearchModalInfo(null)}
        />
      )}
    </div>
  );
}


