import toast from 'react-hot-toast';
import { useState, useEffect, useRef, KeyboardEvent } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { decksApi, notesApi, aiApi } from '../services/api';
import { handleImagePaste, compressImageFromPaste } from '../utils/imageUtils';
import { lookupDefinition, lookupImage } from '../utils/definitionService';
import ImageSearchModal from '../components/ImageSearchModal';
import { Deck } from '../types';
import { SegmentedControl } from '../components/ui/segmented-control';
import { Sparkles, Bot, Image, Folder, Search, ChevronDown, X, ArrowLeft } from 'lucide-react';
import { Button } from '../components/ui/button';
import BottomSheet from '../components/BottomSheet';

const NOTE_TYPES = [
  { id: 'basic', name: 'B├ísica', description: 'Frente y dorso simple' },
  { id: 'reverse', name: 'B├ísica + Reversa', description: 'Genera 2 tarjetas' },
];

const formatMovedText = (html: string) => {
  const text = (html || '').replace(/<[^>]*>/g, '').trim();
  if (!text) return '';
  const titleCased = text.split(/\s+/).map(w => w.charAt(0).toUpperCase() + w.toLowerCase().slice(1)).join(' ');
  return `<div style="font-size: 1.25em; text-align: center;" data-auto="true"><strong>${titleCased}</strong></div>`;
};

const isAutoGenerated = (html: string) => {
  if (typeof html !== 'string') return false;
  return html.includes('data-auto="true"');
};

export default function AddCard() {
  const { deckId: paramDeckId } = useParams<{ deckId: string }>();
  const navigate = useNavigate();
    
  const [decks, setDecks] = useState<Deck[]>([]);
  const [selectedDeckId, setSelectedDeckId] = useState<string>(paramDeckId || '');
  const [selectedType, setSelectedType] = useState<string>('basic');
  const [addMode, setAddMode] = useState<'single' | 'mass'>('single');
  const [fields, setFields] = useState({ front: '', back: '' });
  const [tags, setTags] = useState<string[]>([]);
  const [tagInput, setTagInput] = useState<string>('');
  const [massInput, setMassInput] = useState<string>('');
  const [saving, setSaving] = useState<boolean>(false);
  const [massGenerating, setMassGenerating] = useState<boolean>(false);
  const [showDeckSelector, setShowDeckSelector] = useState(false);
  const [showTypeSelector, setShowTypeSelector] = useState(false);
  
  const [lookingUpDef, setLookingUpDef] = useState<boolean>(false);
  const [lookingUpImage, setLookingUpImage] = useState<boolean>(false);

  const [imageSearchModalInfo, setImageSearchModalInfo] = useState<{ field: 'front' | 'back', query: string } | null>(null);
  
  const frontFileRef = useRef<HTMLInputElement>(null);
  const backFileRef = useRef<HTMLInputElement>(null);
  const tagInputRef = useRef<HTMLInputElement>(null);
  const frontContentRef = useRef<HTMLDivElement>(null);
  const backContentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    decksApi.getAll().then(data => {
      setDecks(data);
      if (!selectedDeckId && data.length > 0) setSelectedDeckId(data[0].id);
    });
  }, [selectedDeckId]);

  const clearEditor = () => {
    setFields({ front: '', back: '' });
    if (frontContentRef.current) frontContentRef.current.innerHTML = '';
    if (backContentRef.current) backContentRef.current.innerHTML = '';
  };

  const insertHtmlAtCursor = (html: string, contentRef: React.RefObject<HTMLDivElement | null>) => {
    if (!contentRef.current) return;
    contentRef.current.focus();
    let selection = window.getSelection();
    if (!selection || selection.rangeCount === 0) return;
    let range = selection.getRangeAt(0);
    
    const isWithinRef = contentRef.current.contains(range.commonAncestorContainer);
    if (!isWithinRef) {
      range = document.createRange();
      range.selectNodeContents(contentRef.current);
      range.collapse(false);
      selection.removeAllRanges();
      selection.addRange(range);
    }
    
    range.deleteContents();
    const el = document.createElement("div");
    el.innerHTML = html;
    const frag = document.createDocumentFragment();
    let node, lastNode;
    while ((node = el.firstChild)) {
      lastNode = frag.appendChild(node);
    }
    range.insertNode(frag);
    if (lastNode) {
      range = range.cloneRange();
      range.setStartAfter(lastNode);
      range.collapse(true);
      selection.removeAllRanges();
      selection.addRange(range);
    }
  };

  const handleFieldChange = (field: 'front' | 'back') => (e: React.FormEvent<HTMLDivElement>) => {
    let content = e.currentTarget.innerHTML;
    if (content === '<br>') content = '';
    
    if (field === 'back' && isAutoGenerated(fields.front) && !content) {
      const movedHtml = formatMovedText(fields.front);
      setFields(prev => ({ ...prev, front: '', back: movedHtml }));
      if (frontContentRef.current) frontContentRef.current.innerHTML = '';
      if (backContentRef.current) backContentRef.current.innerHTML = movedHtml;
      setTimeout(() => {
        const sel = window.getSelection();
        if (!sel || !backContentRef.current) return;
        const range = document.createRange();
        range.selectNodeContents(backContentRef.current);
        range.collapse(false);
        sel.removeAllRanges();
        sel.addRange(range);
      }, 0);
      return;
    }
    
    setFields(prev => ({ ...prev, [field]: content }));
  };

  const handlePaste = (field: 'front' | 'back') => async (e: React.ClipboardEvent<HTMLDivElement>) => {
    handleImagePaste(e, () => {
      setFields(prev => ({ ...prev, [field]: field === 'front' && frontContentRef.current ? frontContentRef.current.innerHTML : backContentRef.current ? backContentRef.current.innerHTML : '' }));
    });
  };

  const handleFileSelected = (field: 'front' | 'back', e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    compressImageFromPaste(file).then((base64: string) => {
      const imgHtml = `<img src="${base64}" />`;
      if (field === 'front') insertHtmlAtCursor(imgHtml, frontContentRef);
      else insertHtmlAtCursor(imgHtml, backContentRef);
      setFields(prev => ({ ...prev, [field]: field === 'front' && frontContentRef.current ? frontContentRef.current.innerHTML : backContentRef.current ? backContentRef.current.innerHTML : '' }));
      e.target.value = '';
    });
  };

  const handleGalleryPick = (field: 'front' | 'back') => {
    if (field === 'front') frontFileRef.current?.click();
    else backFileRef.current?.click();
  };

  const handleOpenImageSearch = (field: 'front' | 'back') => {
    const query = (fields[field] || '').replace(/<[^>]*>/g, '').trim() || (field === 'back' ? (fields.front || '').replace(/<[^>]*>/g, '').trim() : '');
    setImageSearchModalInfo({ field, query });
  };

  const handleImageSearchSelect = (base64: string, field: 'front' | 'back') => {
    const imgHtml = `<img src="${base64}" />`;
    if (field === 'front') insertHtmlAtCursor(imgHtml, frontContentRef);
    else insertHtmlAtCursor(imgHtml, backContentRef);
    setFields(prev => ({ ...prev, [field]: field === 'front' && frontContentRef.current ? frontContentRef.current.innerHTML : backContentRef.current ? backContentRef.current.innerHTML : '' }));
  };

  const handleDefinition = async () => {
    const term = (fields.front || '').replace(/<[^>]*>/g, '').trim();
    if (!term) return toast.error('Escribe un t├®rmino en el frente primero');
    setLookingUpDef(true);
    try {
      const def = await lookupDefinition(term);
      if (def?.definition) {
        if (frontContentRef.current) frontContentRef.current.innerHTML = def.definition;
        if (backContentRef.current) backContentRef.current.innerHTML = term;
        setFields(prev => ({ ...prev, front: def.definition, back: term }));
      }
    } catch (e: unknown) {
      toast.error(e instanceof Error ? e.message : 'Error buscando definicion');
    } finally {
      setLookingUpDef(false);
    }
  };

  const handleAutoImage = async () => {
    const term = (fields.front || '').replace(/<[^>]*>/g, '').trim();
    if (!term) return toast.error('Escribe un t├®rmino en el frente primero');
    setLookingUpImage(true);
    try {
      const url = await lookupImage(term);
      if (url) {
        const imgHtml = `<img src="${url}" />`;
        if (frontContentRef.current) frontContentRef.current.innerHTML = imgHtml;
        if (backContentRef.current) backContentRef.current.innerHTML = term;
        setFields(prev => ({ ...prev, front: imgHtml, back: term }));
      } else {
        toast.error('No se encontr├│ imagen');
      }
    } catch (e: unknown) {
      toast.error(e instanceof Error ? e.message : 'Error buscando imagen');
    } finally {
      setLookingUpImage(false);
    }
  };

  const handleAdd = async (closeAfter: boolean) => {
    if (!selectedDeckId) return toast.error('Selecciona un mazo');
    if (!fields.front.trim() || !fields.back.trim()) return toast.error('El frente y el dorso son obligatorios');
    
    setSaving(true);
    try {
      const fieldsJson = JSON.stringify({ front: fields.front, back: fields.back });
      await notesApi.create({
        deckId: selectedDeckId,
        noteType: selectedType,
        fieldsJson,
        tags: tags.join(',')
      });
      toast.success('Tarjeta a├▒adida');
      clearEditor();
      if (closeAfter) navigate('/');
    } catch (e: unknown) {
      toast.error(e instanceof Error ? e.message : 'Error al guardar');
    } finally {
      setSaving(false);
    }
  };

  const handleMassAdd = async () => {
    if (!massInput.trim() || !selectedDeckId) return;
    setMassGenerating(true);
    try {
      const lines = massInput.split(/[\n,]+/).map(s => s.trim()).filter(Boolean);
      if (lines.length === 0) return;
      
      const res = await aiApi.massDefine(lines.join('\n')) as unknown as { front: string; back: string; }[];
      if (!res || !Array.isArray(res) || res.length === 0) {
        throw new Error('No se generaron tarjetas');
      }
      
      let count = 0;
      for (const card of res) {
        await notesApi.create({
          deckId: selectedDeckId,
          noteType: 'basic',
          fieldsJson: JSON.stringify({ front: card.front, back: card.back }),
          tags: tags.join(',')
        });
        count++;
      }
      
      toast.success(`┬íGeneradas ${count} tarjetas!`);
      setMassInput('');
    } catch (e: unknown) {
      toast.error(e instanceof Error ? e.message : 'Error al generar masa');
    } finally {
      setMassGenerating(false);
    }
  };

  const handleTagKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault();
      const tag = tagInput.trim().toLowerCase().replace(/[^a-z0-9-]/g, '');
      if (tag && !tags.includes(tag)) setTags([...tags, tag]);
      setTagInput('');
    } else if (e.key === 'Backspace' && tagInput === '' && tags.length > 0) {
      setTags(tags.slice(0, -1));
    }
  };
  const removeTag = (t: string) => setTags(tags.filter(x => x !== t));

  useEffect(() => {
    const handler = (e: globalThis.KeyboardEvent) => {
      if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) { 
        e.preventDefault(); 
        if (addMode === 'single') handleAdd(false); 
        else handleMassAdd();
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [fields, selectedDeckId, selectedType, tags, massInput, addMode]);

  return (
    <div className="fade-in pb-12">

      <div className="flex items-center gap-3 mb-6">
        <Button variant="ghost" size="icon" onClick={() => navigate(-1)} className="-ml-2">
          <ArrowLeft className="w-5 h-5" />
        </Button>
        <div>
          <h2 className="text-xl font-bold m-0">Añadir Tarjeta</h2>
        </div>
      </div>

              
        <SegmentedControl
          options={[
            { label: 'Una a una', value: 'single' },
            { label: 'En Masa', value: 'mass' }
          ]}
          value={addMode}
          onChange={(val) => setAddMode(val as 'single' | 'mass')}
          className="mb-6 max-w-sm mx-auto"
        />

        <div className="card" style={{ marginBottom: '1.5rem' }}>

        <input ref={frontFileRef} type="file" accept="image/*" style={{ display: 'none' }} onChange={(e) => handleFileSelected('front', e)} />
        <input ref={backFileRef} type="file" accept="image/*" style={{ display: 'none' }} onChange={(e) => handleFileSelected('back', e)} />

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
          <div>
            <label className="form-label" style={{ margin: 0, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>MAZO</label>
            <button 
                type="button"
                className="form-input" 
                onClick={() => setShowDeckSelector(true)}
                style={{ width: '100%', height: '42px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'var(--bg-input)' }}
              >
                <span>{decks.find(d => d.id === selectedDeckId)?.name || 'Seleccionar mazo...'}</span>
                <ChevronDown className="w-4 h-4 opacity-50" />
              </button>
          </div>
          
          {addMode === 'single' && (
            <div>
              <label className="form-label" style={{ margin: 0, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>TIPO DE NOTA</label>
              <button 
                  type="button"
                  className="form-input" 
                  onClick={() => setShowTypeSelector(true)}
                  style={{ width: '100%', height: '42px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'var(--bg-input)' }}
                >
                  <span>{NOTE_TYPES.find(t => t.id === selectedType)?.name || 'B├ísica'}</span>
                  <ChevronDown className="w-4 h-4 opacity-50" />
                </button>
            </div>
          )}
        </div>
      </div>

      {addMode === 'mass' ? (
        <div className="card" style={{ marginBottom: '1.5rem' }}>
          <p style={{ margin: '0 0 16px 0', fontSize: '0.9rem', color: 'var(--text-muted)', textAlign: 'center' }}>
              Escribe o pega una lista de conceptos (separados por comas o saltos de l├¡nea) para autogenerar las tarjetas.
            </p>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', marginBottom: '24px' }}>
            <label className="form-label" style={{ margin: 0, textTransform: 'uppercase', letterSpacing: '0.5px' }}>Lista de Conceptos</label>
            <textarea
              className="form-input"
              style={{ minHeight: '200px', padding: '12px', resize: 'vertical' }}
              value={massInput}
              onChange={e => setMassInput(e.target.value)}
              placeholder="Ejemplo:&#10;Polimorfismo&#10;Herencia&#10;Encapsulaci├│n&#10;Abstracci├│n"
            />
          </div>
          
          <button 
            className="btn btn-primary" 
            style={{ width: '100%', padding: '16px', fontSize: '1.1rem' }} 
            onClick={handleMassAdd}
            disabled={massGenerating}
          >
            {massGenerating ? <span className="spinner-sm" /> : <span className="flex items-center justify-center gap-2"><Sparkles className="w-5 h-5" /> Generar y Añadir (Ctrl+Enter)</span>}
          </button>
        </div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', gap: '1.5rem' }}>
          
          <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
            {/* Front */}
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8, flexWrap: 'wrap', gap: '8px' }}>
                <label className="form-label" style={{ margin: 0, textTransform: 'uppercase', letterSpacing: '0.5px' }}>Frente</label>
                <div style={{ display: 'flex', gap: '8px' }}>
                  <button type="button" className="btn" style={{ padding: '6px 8px', fontSize: '0.75rem', background: 'var(--bg-secondary)', border: '1px solid var(--border-medium)', borderRadius: '10px', color: 'var(--text-primary)', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '4px', minWidth: '60px' }} onClick={handleDefinition} disabled={lookingUpDef}>
                    <Sparkles className="w-4 h-4 mb-1" />
                    <span style={{ lineHeight: 1, fontWeight: 600 }}>{lookingUpDef ? '...' : 'Def. IA'}</span>
                  </button>
                  <button type="button" className="btn" style={{ padding: '6px 8px', fontSize: '0.75rem', background: 'var(--bg-secondary)', border: '1px solid var(--border-medium)', borderRadius: '10px', color: 'var(--text-primary)', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '4px', minWidth: '60px' }} onClick={handleAutoImage} disabled={lookingUpImage}>
                    <Image className="w-4 h-4 mb-1" />
                    <span style={{ lineHeight: 1, fontWeight: 600 }}>{lookingUpImage ? '...' : 'Auto'}</span>
                  </button>
                  <button type="button" className="btn" style={{ padding: '6px 8px', fontSize: '0.75rem', background: 'var(--bg-secondary)', border: '1px solid var(--border-medium)', borderRadius: '10px', color: 'var(--text-primary)', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '4px', minWidth: '60px' }} onClick={() => handleGalleryPick('front')} title="Galer├¡a">
                    <Folder className="w-4 h-4 mb-1" />
                    <span style={{ lineHeight: 1, fontWeight: 600 }}>Galer├¡a</span>
                  </button>
                  <button type="button" className="btn" style={{ padding: '6px 8px', fontSize: '0.75rem', background: 'var(--bg-secondary)', border: '1px solid var(--border-medium)', borderRadius: '10px', color: 'var(--text-primary)', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '4px', minWidth: '60px' }} onClick={() => handleOpenImageSearch('front')} title="Wikipedia">
                    <Search className="w-4 h-4 mb-1" />
                    <span style={{ lineHeight: 1, fontWeight: 600 }}>Buscar</span>
                  </button>
                </div>
              </div>
              <div 
                className="form-input" 
                style={{ minHeight: "120px" }}
                contentEditable 
                ref={frontContentRef}
                onInput={handleFieldChange('front')} 
                onPaste={handlePaste('front')}
              />
            </div>

            {/* Back */}
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8, flexWrap: 'wrap', gap: '8px' }}>
                <label className="form-label" style={{ margin: 0, textTransform: 'uppercase', letterSpacing: '0.5px' }}>Dorso</label>
                <div style={{ display: 'flex', gap: '8px' }}>
                  <button type="button" className="btn" style={{ padding: '6px 8px', fontSize: '0.75rem', background: 'var(--bg-secondary)', border: '1px solid var(--border-medium)', borderRadius: '10px', color: 'var(--text-primary)', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '4px', minWidth: '60px' }} onClick={() => handleGalleryPick('back')} title="Galer├¡a">
                    <Folder className="w-4 h-4 mb-1" />
                    <span style={{ lineHeight: 1, fontWeight: 600 }}>Galer├¡a</span>
                  </button>
                  <button type="button" className="btn" style={{ padding: '6px 8px', fontSize: '0.75rem', background: 'var(--bg-secondary)', border: '1px solid var(--border-medium)', borderRadius: '10px', color: 'var(--text-primary)', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '4px', minWidth: '60px' }} onClick={() => handleOpenImageSearch('back')} title="Wikipedia">
                    <Search className="w-4 h-4 mb-1" />
                    <span style={{ lineHeight: 1, fontWeight: 600 }}>Buscar</span>
                  </button>
                </div>
              </div>
              <div 
                className="form-input" 
                style={{ minHeight: "120px" }}
                contentEditable 
                ref={backContentRef}
                onInput={handleFieldChange('back')} 
                onPaste={handlePaste('back')}
              />
            </div>

            {/* Tags */}
            <div>
              <label style={{ display: 'block', fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: 8, fontWeight: 600 }}>ETIQUETAS</label>
              <div className="form-input" style={{ display: 'flex', flexWrap: 'wrap', gap: '8px', minHeight: '44px', padding: '8px 12px', alignItems: 'center' }} onClick={() => tagInputRef.current?.focus()}>
                {tags.map(tag => (
                  <span key={tag} style={{ background: 'var(--accent-color)', color: 'white', padding: '2px 8px', borderRadius: '12px', fontSize: '0.8rem', display: 'flex', alignItems: 'center', gap: '4px' }}>
                    {tag}
                    <span style={{ cursor: 'pointer', opacity: 0.7 }} onClick={(e) => { e.stopPropagation(); removeTag(tag); }}><X className="w-3 h-3" /></span>
                  </span>
                ))}
                <input
                  ref={tagInputRef}
                  style={{ flex: 1, minWidth: '120px', background: 'transparent', border: 'none', outline: 'none', color: 'inherit' }}
                  placeholder={tags.length === 0 ? 'A├▒adir etiquetas...' : ''}
                  value={tagInput}
                  onChange={e => setTagInput(e.target.value)}
                  onKeyDown={handleTagKeyDown}
                />
              </div>
            </div>

            <div style={{ display: 'flex', gap: '12px', marginTop: '8px' }}>
              <button className="btn btn-primary" style={{ flex: 1 }} onClick={() => handleAdd(false)} disabled={saving}>
                {saving ? 'Guardando...' : 'A├▒adir (Ctrl+Enter)'}
              </button>
              <button className="btn btn-secondary" style={{ flex: 1 }} onClick={() => handleAdd(true)} disabled={saving}>
                A├▒adir y Cerrar
              </button>
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column' }}>
            <div style={{ fontSize: '0.75rem', fontWeight: 'bold', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '12px' }}>Vista Previa</div>
            <div className="card" style={{ flex: 1, padding: '1.5rem', display: 'flex', flexDirection: 'column', minHeight: '400px' }}>
              <div style={{ textAlign: 'center', fontSize: '1.1rem' }} dangerouslySetInnerHTML={{ __html: fields.front || '<span style="color:var(--text-dim)">Pregunta...</span>' }} />
              <div style={{ height: '1px', width: '66%', background: 'var(--border-color)', margin: '24px auto' }} />
              <div style={{ textAlign: 'center', fontSize: '1.1rem', flex: 1 }} dangerouslySetInnerHTML={{ __html: fields.back || '<span style="color:var(--text-dim)">Respuesta...</span>' }} />
              {tags.length > 0 && (
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px', justifyContent: 'center', marginTop: '24px', paddingTop: '16px', borderTop: '1px solid var(--border-color)' }}>
                  {tags.map(tag => <span key={tag} style={{ border: '1px solid var(--border-color)', padding: '2px 8px', borderRadius: '4px', fontSize: '0.7rem' }}>{tag}</span>)}
                </div>
              )}
            </div>
          </div>
          
        </div>
      )}


      <BottomSheet
        isOpen={showDeckSelector}
        onClose={() => setShowDeckSelector(false)}
        title="Seleccionar Mazo"
      >
        <div className="bottom-sheet-grid" style={{ maxHeight: '60vh', overflowY: 'auto' }}>
          {decks.map(d => (
            <button
              key={d.id}
              className={`bottom-sheet-item ${selectedDeckId === d.id ? 'active' : ''}`}
              onClick={() => { setSelectedDeckId(d.id); setShowDeckSelector(false); }}
            >
              <span>{d.name}</span>
            </button>
          ))}
        </div>
      </BottomSheet>

      <BottomSheet
        isOpen={showTypeSelector}
        onClose={() => setShowTypeSelector(false)}
        title="Tipo de Nota"
      >
        <div className="bottom-sheet-grid">
          {NOTE_TYPES.map(t => (
            <button
              key={t.id}
              className={`bottom-sheet-item ${selectedType === t.id ? 'active' : ''}`}
              onClick={() => { setSelectedType(t.id); clearEditor(); setShowTypeSelector(false); }}
            >
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start' }}>
                <span>{t.name}</span>
                <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{t.description}</span>
              </div>
            </button>
          ))}
        </div>
      </BottomSheet>

      {imageSearchModalInfo && (
        <ImageSearchModal
          isOpen={true}
          initialQuery={imageSearchModalInfo.query}
          onSelect={(base64: string) => handleImageSearchSelect(base64, imageSearchModalInfo.field)}
          onClose={() => setImageSearchModalInfo(null)}
        />
      )}
    </div>
  );
}







